### ISSUE TITLE
I built a signed apk of it and tested it on 4 devices. 2 emulators and 2 real devices it worked fine in one real device only in other 3 it get crashed

### ISSUE THREAD

**Issue by NomanBaigA** [darkmoonight/Rain#130]
Flutter initialization failed.
                                                                                                    java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/lib/x86, /data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
                                                                                                    	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
                                                                                                    	at c2.f.g(Unknown Source:28)
                                                                                                    	at io.flutter.embedding.engine.d.<init>(Unknown Source:35)
                                                                                                    	at io.flutter.embedding.android.e.I(Unknown Source:172)
                                                                                                    	at io.flutter.embedding.android.e.q(Unknown Source:7)
                                                                                                    	at io.flutter.embedding.android.d.onCreate(Unknown Source:13)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7009)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7000)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/lib/x86, /data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1657)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
                                                                                                    	at c2.f$a.b(Unknown Source:18)
                                                                                                    	at c2.f$a.call(Unknown Source:0)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
2023-10-24 02:08:48.846 19827-19827 AndroidRuntime          com.yoshi.rain                       D  Shutting down VM
2023-10-24 02:08:48.851 19827-19827 AndroidRuntime          com.yoshi.rain                       E  FATAL EXCEPTION: main
                                                                                                    Process: com.yoshi.rain, PID: 19827
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yoshi.rain/com.yoshi.rain.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/lib/x86, /data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                                    Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/lib/x86, /data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
                                                                                                    	at c2.f.g(Unknown Source:478)
                                                                                                    	at io.flutter.embedding.engine.d.<init>(Unknown Source:35)
                                                                                                    	at io.flutter.embedding.android.e.I(Unknown Source:172)
                                                                                                    	at io.flutter.embedding.android.e.q(Unknown Source:7)
                                                                                                    	at io.flutter.embedding.android.d.onCreate(Unknown Source:13)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7009)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7000)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:164) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
                                                                                                    Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/lib/x86, /data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
                                                                                                    	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
                                                                                                    	at c2.f.g(Unknown Source:28)
                                                                                                    	at io.flutter.embedding.engine.d.<init>(Unknown Source:35) 
                                                                                                    	at io.flutter.embedding.android.e.I(Unknown Source:172) 
                                                                                                    	at io.flutter.embedding.android.e.q(Unknown Source:7) 
                                                                                                    	at io.flutter.embedding.android.d.onCreate(Unknown Source:13) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7009) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7000) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:164) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/lib/x86, /data/app/com.yoshi.rain--15U-ivLXhboVZCkFBeO4Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1657)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
                                                                                                    	at c2.f$a.b(Unknown Source:18)
                                                                                                    	at c2.f$a.call(Unknown Source:0)

**Comment by NomanBaigA** [comment]
Debug version is working properly in all devices

**Comment by NomanBaigA** [comment]
I also tried it from Google Play and it's working fine. It's strange that the same app is not working from the source code but working fine from Stores. Please Help

**Comment by NeuroException** [comment]
If you would've read the logs properly, you would've noticed that you are missing a library.

**Comment by Leonavichus** [comment]
I downloaded the project again from github, entered the flutter pub get command and added key.properties to the android folder and everything works fine. I do not know what your problems are.

**Comment by NomanBaigA** [comment]
> I downloaded the project again from github, entered the flutter pub get command and added key.properties to the android folder and everything works fine. I do not know what your problems are.


Problem is coming with signed apk when we are trying to install and open that signed apk in device app is getting crashed with the error I shared. The debug version is working completely fine. If you are considering all these points and you are not facing this crash, can you please some tips or share some suggestions maybe I am doing something wrong or something wrong with my flutter

**Comment by Leonavichus** [comment]
what version of flutter do you have?

**Comment by NomanBaigA** [comment]
> what version of flutter do you have?

Flutter 3.13.8, 
Dart 3.1.4

**Comment by Leonavichus** [comment]
Then I do not know what the problem is

**Comment by NomanBaigA** [comment]
> Then I do not know what the problem is

During building I am getting these messages - (Maybe this is causing that crash)

"e: C:/Users/USER/Desktop/CheckKar/Rain-v.3.6/build/flutter_timezone/.transforms/bd0d96e3ae6dae3966d7a60f5a51aa3d/transformed/out/jars/classes.jar!/META-INF/flutter_timezone_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: C:/Users/USER/Desktop/CheckKar/Rain-v.3.6/build/dynamic_color/.transforms/a3069b1d6caef567ca5effdab79e1600/transformed/out/jars/classes.jar!/META-INF/dynamic_color_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: C:/Users/USER/Desktop/CheckKar/Rain-v.3.6/build/home_widget/.transforms/c21f7eda768a6f1d38460c8a52499322/transformed/out/jars/classes.jar!/META-INF/home_widget_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: C:/Users/USER/Desktop/CheckKar/Rain-v.3.6/build/package_info_plus/.transforms/66d70735ddf33f2e3cbe092bcb9ce5fc/transformed/out/jars/classes.jar!/META-INF/package_info_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: C:/Users/USER/Desktop/CheckKar/Rain-v.3.6/build/workmanager/.transforms/2636aa67fa253cf67f54b0a282914ec9/transformed/out/jars/classes.jar!/META-INF/workmanager_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: C:/Users/USER/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: C:/Users/USER/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: C:/Users/USER/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: C:/Users/USER/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.9.10/dafaf2c27f27c09220cee312df10917d9a5d97ce/kotlin-stdlib-common-1.9.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1."

**Comment by Leonavichus** [comment]
No, these errors are not related to this. They just say that it is necessary to update the gradle.

**Comment by NomanBaigA** [comment]
> couldn't find "libflutter.so"

Ok, Thanks... Seems like I am stuck because I tried to search this error "couldn't find "libflutter.so"" but lots of people are stuck with this error and there is no proper solution for it..

**Comment by shatanikmahanty** [comment]
@NomanBaigA can you check if adding

```gradle
buildTypes {
    release {
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86_64'
        }
    }
}
```

in `android\app\build.gradle` solves your problem.

**Comment by NomanBaigA** [comment]
> @NomanBaigA can you check if adding
> 
> ```groovy-gradle
> buildTypes {
>     release {
>         ndk {
>             abiFilters 'armeabi-v7a','arm64-v8a','x86_64'
>         }
>     }
> }
> ```
> 
> in `android\app\build.gradle` solves your problem.
> 
> The release group is already there, so just adding ndk should be fine

Thanks for sharing, actually i tried lots of solutions already from the internet

**Comment by shatanikmahanty** [comment]
Could be related to https://github.com/flutter/flutter/issues/90586
